# Generated by Django 3.1.5 on 2021-01-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre maquina')),
                ('nombre_clave', models.CharField(max_length=40, unique=True, verbose_name='nombre clave')),
                ('peso', models.CharField(max_length=255, verbose_name='peso')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='descripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
